baseURL = 'https://xyc-gamma.vercel.app/' # 建议以后改成你自定义的域名
languageCode = 'en-us'
title = 'Yucheng Xu' # 浏览器标签页显示的标题
theme = 'PaperMod'

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
    env = "production"
    title = "Yucheng Xu"
    description = "Build my city."
    keywords = ["Blog", "Portfolio", "Python"]
    author = "Yucheng"

    # 进入“个人名片模式”
    [params.profileMode]
        enabled = true
        title = "Hello，I'm Cade 👋"
        subtitle = "Geographer/ Graduate Student/ Python Developer"
        displayFullContent = false
        imageUrl = "img/avatar.jpg" # 头像路径，稍后教你放图
        imageWidth = 150
        imageHeight = 180

        # 首页上的功能按钮
        [[params.profileMode.buttons]]
            name = "View my projects"
            url = "/posts/"
        [[params.profileMode.buttons]]
            name = "About me"
            url = "/about/"

    # 社交媒体链接（会自动显示图标）
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/xycade"
    [[params.socialIcons]]
        name = "email"
        url = "mailto:xyc1477@163.com"

# 导航栏配置
[[menu.main]]
    name = "Article"
    url = "/posts/"
    weight = 10
[[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 20